// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 87RqUXPRhfuJ9yTiA95WNo
// Component: azcCSNhOwt

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import VideoEmbed from "../../VideoEmbed"; // plasmic-import: rqsyovS14ray/component

import { useScreenVariants as useScreenVariantszjlABz8Zg1KZ1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZjlABz_8Zg1kZ1/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 87RqUXPRhfuJ9yTiA95WNo/projectcss
import sty from "./PlasmicDiscourseGraphsNew.module.css"; // plasmic-import: azcCSNhOwt/css

createPlasmicElementProxy;

export type PlasmicDiscourseGraphsNew__VariantMembers = {};
export type PlasmicDiscourseGraphsNew__VariantsArgs = {};
type VariantPropType = keyof PlasmicDiscourseGraphsNew__VariantsArgs;
export const PlasmicDiscourseGraphsNew__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDiscourseGraphsNew__ArgsType = {};
type ArgPropType = keyof PlasmicDiscourseGraphsNew__ArgsType;
export const PlasmicDiscourseGraphsNew__ArgProps = new Array<ArgPropType>();

export type PlasmicDiscourseGraphsNew__OverridesType = {
  root?: Flex__<"div">;
  videoEmbed?: Flex__<typeof VideoEmbed>;
};

export interface DefaultDiscourseGraphsNewProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDiscourseGraphsNew__RenderFunc(props: {
  variants: PlasmicDiscourseGraphsNew__VariantsArgs;
  args: PlasmicDiscourseGraphsNew__ArgsType;
  overrides: PlasmicDiscourseGraphsNew__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszjlABz8Zg1KZ1()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicDiscourseGraphsNew.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicDiscourseGraphsNew.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicDiscourseGraphsNew.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___5NeXx)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__y9UIv)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"327px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/discourse_graphs/images/dgLogoPrimaryLightPng.png",
                fullWidth: 571,
                fullHeight: 240,
                aspectRatio: undefined
              }}
            />

            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__stGx)}
            >
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__zjO8
                )}
                component={Link}
                href={"/#about"}
                platform={"nextjs"}
              >
                {"About"}
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link___9CSu8
                )}
                component={Link}
                href={"/#resources"}
                platform={"nextjs"}
              >
                {"Resources"}
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__dyvZ2
                )}
                component={Link}
                href={"/#talks"}
                platform={"nextjs"}
              >
                {"Talks"}
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__x7Aua
                )}
                component={Link}
                href={"/#contact"}
                platform={"nextjs"}
              >
                {"Contact"}
              </PlasmicLink__>
            </Stack__>
          </Stack__>
          <div className={classNames(projectcss.all, sty.freeBox__u4YHv)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__b1HZe)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___31ZgN
                )}
              >
                <React.Fragment>
                  <React.Fragment>{"The\n"}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#5F57C0" }}
                  >
                    {"Discourse Graphs"}
                  </span>
                  <React.Fragment>{"\n"}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#F1F1F1" }}
                  >
                    {"Starter Pack"}
                  </span>
                </React.Fragment>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__oNffp)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__gyeXm)}
              id={"about"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qCpDt
                )}
              >
                {
                  "Discourse Graphs are a tool and ecosystem for collaborative knowledge synthesis "
                }
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wu1Ay)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___2YgmN)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ifpo
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 500 }}
                      >
                        {"Discourse Graphs"}
                      </span>
                      <React.Fragment>
                        {
                          " are an information model that enables researchers and communicators to map their ideas and arguments in a modular, composable graph format."
                        }
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                </Stack__>
                <div className={classNames(projectcss.all, sty.freeBox__faSxo)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__foVeG)}
                    displayHeight={"217px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"530px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/discourse_graphs/images/dgraphExampleBans1Png.png",
                      fullWidth: 1555,
                      fullHeight: 684,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__act)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qIrl)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sV5Hv
                  )}
                >
                  {
                    "Better infrastructure for scientific synthesis & communication"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hvA58
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Discourse Graphs"}
                    </span>
                    <React.Fragment>
                      {
                        " allow researchers to break the scientific research process into its atomic elements in a way that can be shared, remixed, and updated.\n\nDistinguishing evidence (the empirical observation) from claim (the proposed answer) leaves space for multiple interpretations."
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </Stack__>
              <div className={classNames(projectcss.all, sty.freeBox__owfHf)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___1TlrO)}
                  displayHeight={"233px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/discourse_graphs/images/dgSchemaPng.png",
                    fullWidth: 1682,
                    fullHeight: 1020,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__uN81V)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sZcA)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g3AS
                  )}
                >
                  {"Synthesize and Update"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dEoan
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Discourse Graphs"}
                    </span>
                    <React.Fragment>
                      {
                        " enable researchers to exchange knowledge in a form that makes it straightforward to construct, update, and find.\n\nLike Lego\u2122\ufe0f bricks, the modular components of the "
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Discourse Graphs"}
                    </span>
                    <React.Fragment>
                      {
                        " data model make it easy to choose which parts of a scientific project you wish to share and build upon."
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </Stack__>
              <div className={classNames(projectcss.all, sty.freeBox__llIlp)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__i11P8)}
                  displayHeight={"233px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/discourse_graphs/images/image3Svg.undefined",
                    fullWidth: 133,
                    fullHeight: 150,
                    aspectRatio: 0.888545
                  }}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__rAyvs)}>
              <div className={classNames(projectcss.all, sty.freeBox__mgOem)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___0G1HS)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__wDfb3)}
                    displayHeight={"200px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"auto"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/discourse_graphs/images/screenshot20241110At62800PmPng.png",
                      fullWidth: 2056,
                      fullHeight: 874,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__bHa)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ubIdZ
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-MwpQlpeDq)" }}
                    >
                      {"Liberate your findings"}
                    </span>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__djS
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {"Rather than being organized hierarchically, "}
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"discourse graphs "}
                    </span>
                    <React.Fragment>
                      {
                        'adopt a grassroots organization, which better matches the iterative and nonlinear process of knowledge generation.  \n\nThe schema adds enough structure for you to revisit "high signal" findings as "the minimal shareable insight" for others to build on.\n\nAs such, '
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 600 }}
                    >
                      {
                        "discourse graphs provide a needed coordination layer for decentralized science."
                      }
                    </span>
                  </React.Fragment>
                </div>
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___3HDpb)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__gvTvZ)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gS9AN
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-R2BTfMOkE)" }}
                    >
                      {"Client-Agnostic & Researcher-aligned"}
                    </span>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bYw1F
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Discourse Graphs"}
                    </span>
                    <React.Fragment>
                      {
                        " are a decentralized knowledge exchange protocol designed to be implemented and owned by researchers \u2014 rather than publishers \u2014 to share results at all stages of the scientific process.\n\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Discourse Graphs"}
                    </span>
                    <React.Fragment>{" are "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic" }}
                    >
                      {"client-agnostic"}
                    </span>
                    <React.Fragment>
                      {
                        " with decentralized push-pull storage & and can be implemented in any networked notebook software (Roam, Notion, Obsidian, etc.), allowing researchers to collaborate widely while using the tool of their choice.\n\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Discourse Graphs"}
                    </span>
                    <React.Fragment> </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic" }}
                    >
                      {"support and incentivize knowledge sharing"}
                    </span>
                    <React.Fragment>
                      {
                        " by making it easy to push to and pull from a shared knowledge graph \u2014 and to claim credit for many more types of contributions.\n\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Discourse Graphs "}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 400 }}
                    >
                      {"are like github for scientific communication."}
                    </span>
                  </React.Fragment>
                </div>
              </Stack__>
              <div className={classNames(projectcss.all, sty.freeBox___3Vxp)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__iXr1)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/discourse_graphs/images/image4Svg.undefined",
                    fullWidth: 93,
                    fullHeight: 150,
                    aspectRatio: 0.617577
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__tHclC)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/discourse_graphs/images/image5Svg.undefined",
                    fullWidth: 93,
                    fullHeight: 150,
                    aspectRatio: 0.617577
                  }}
                />
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__d27Xo)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___0LC99)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2NKUl
                  )}
                >
                  {"The natural OS for a Cloud Laboratory"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hq3TL
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"The flexible "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Discourse Graph"}
                    </span>
                    <React.Fragment>
                      {
                        " framework has been adapted to coordinate and share active research, helping to lower the barrier for interdisciplinary collaboration.\n\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Lab"}
                    </span>
                    <React.Fragment> </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 500 }}
                    >
                      {"Discourse Graphs"}
                    </span>
                    <React.Fragment>
                      {" can be used to support\n\n"}
                    </React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__qWzQk
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__cxD4Z
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {
                                'identifying gaps in knowledge and tractable "starter projects" for new researchers'
                              }
                            </span>
                          </React.Fragment>
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__dydaa
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {
                                "faster onboarding to existing research projects"
                              }
                            </span>
                          </React.Fragment>
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__cUxB
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {
                                "grassroots generation of knowledge between researchers"
                              }
                            </span>
                          </React.Fragment>
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__kw9Tj
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {
                                "modular communication and attribution of research findings"
                              }
                            </span>
                          </React.Fragment>
                        </li>
                      </ul>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__rP1F)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__n5ODv
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 500 }}
                      >
                        {"\u27a1\ufe0f which leads to "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{
                          fontWeight: 500,
                          color: "var(--token-NFSfQfEfW)"
                        }}
                      >
                        {"lower-friction collaboration"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 500 }}
                      >
                        {"\u21aa\ufe0f and a "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#5F57C0", fontWeight: 500 }}
                      >
                        {"faster discovery & innovation cycle"}
                      </span>
                    </React.Fragment>
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xdFDz)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"760px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/discourse_graphs/images/matsuLabDiscourseGraphSnapshotPng.png",
                      fullWidth: 1952,
                      fullHeight: 1744,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xTqrc
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Snapshot of "}</React.Fragment>
                      {
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__kuSkW
                          )}
                          component={Link}
                          href={"https://matsulab.com/"}
                          platform={"nextjs"}
                        >
                          {"MATSU lab"}
                        </PlasmicLink__>
                      }
                      <React.Fragment>{" discourse graph"}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
              </Stack__>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__zIqJ8)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__tvSq)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sMeFd)}
                id={"resources"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v0So7
                  )}
                >
                  {"Resources"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__rNuhM)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hAbzB)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qEhYa
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <Stack__
                            as={"ul"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__zWUh
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__sQYh
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <PlasmicLink__
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      projectcss.__wab_text,
                                      projectcss.plasmic_default__inline,
                                      sty.link__azBdw
                                    )}
                                    component={Link}
                                    href={
                                      "https://research.protocol.ai/blog/2023/discourse-graphs-and-the-future-of-science/"
                                    }
                                    platform={"nextjs"}
                                  >
                                    {
                                      "Discourse Graphs and the Future of Science"
                                    }
                                  </PlasmicLink__>
                                }
                                <React.Fragment>
                                  {
                                    " by Matt Akamatsu and Evan Miyazono, in conversation with Tom Kalil"
                                  }
                                </React.Fragment>
                              </React.Fragment>
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___4NVbs
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <PlasmicLink__
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      projectcss.__wab_text,
                                      projectcss.plasmic_default__inline,
                                      sty.link__ufaq6
                                    )}
                                    component={Link}
                                    href={
                                      "https://experiment.com/projects/sustainable-coordination-in-research-labs-via-graph-enabled-idea-boards/"
                                    }
                                    platform={"nextjs"}
                                  >
                                    {"Project notes"}
                                  </PlasmicLink__>
                                }
                                <React.Fragment>
                                  {
                                    ": discourse graphs for research lab coordination"
                                  }
                                </React.Fragment>
                              </React.Fragment>
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__veFu5
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <PlasmicLink__
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      projectcss.__wab_text,
                                      projectcss.plasmic_default__inline,
                                      sty.link___9G3Uv
                                    )}
                                    component={Link}
                                    href={"https://arxiv.org/html/2407.20666v2"}
                                    platform={"nextjs"}
                                  >
                                    {"Preprint"}
                                  </PlasmicLink__>
                                }
                                <React.Fragment>
                                  {
                                    " on discourse graph plugin design and use cases"
                                  }
                                </React.Fragment>
                              </React.Fragment>
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___5WK2H
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <PlasmicLink__
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      projectcss.__wab_text,
                                      projectcss.plasmic_default__inline,
                                      sty.link__zOm0W
                                    )}
                                    component={Link}
                                    href={
                                      "https://oasislab.pubpub.org/pub/54t0y9mk/release/3"
                                    }
                                    platform={"nextjs"}
                                  >
                                    {
                                      "Knowledge synthesis: A conceptual model and practical guide"
                                    }
                                  </PlasmicLink__>
                                }
                                <React.Fragment>{""}</React.Fragment>
                              </React.Fragment>
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___8QyQ1
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>
                                  {"Joel Chan on "}
                                </React.Fragment>
                                {
                                  <PlasmicLink__
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      projectcss.__wab_text,
                                      projectcss.plasmic_default__inline,
                                      sty.link__qmgCx
                                    )}
                                    component={Link}
                                    href={
                                      "https://commonplace.knowledgefutures.org/pub/m76tk163/release/1"
                                    }
                                    platform={"nextjs"}
                                  >
                                    <React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{ fontStyle: "italic" }}
                                      >
                                        {
                                          "Sustainable Authorship Models for a Discourse-Based Scholarly Communication Infrastructure"
                                        }
                                      </span>
                                    </React.Fragment>
                                  </PlasmicLink__>
                                }
                                <React.Fragment>{""}</React.Fragment>
                              </React.Fragment>
                            </li>
                          </Stack__>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ok4Xw)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xPftx
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__icJNi
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___4UhQ5
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <PlasmicLink__
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      projectcss.__wab_text,
                                      projectcss.plasmic_default__inline,
                                      sty.link__obgbW
                                    )}
                                    component={Link}
                                    href={
                                      "https://oasis-lab.gitbook.io/roamresearch-discourse-graph-extension"
                                    }
                                    platform={"nextjs"}
                                  >
                                    {"Discourse Graph plugin documentation"}
                                  </PlasmicLink__>
                                }
                                <React.Fragment>
                                  {" for Roam Research\u00a0 "}
                                </React.Fragment>
                              </React.Fragment>
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jQf5D
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__mqvoy
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___7Mi0Y
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <ul
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.ul,
                                      sty.ul___1Kve
                                    )}
                                  >
                                    <li
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.li,
                                        projectcss.__wab_text,
                                        sty.li__cfq1X
                                      )}
                                    >
                                      <React.Fragment>
                                        <React.Fragment>
                                          {"Cybrarian Michael Gartner\u2019s "}
                                        </React.Fragment>
                                        {
                                          <PlasmicLink__
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.a,
                                              projectcss.__wab_text,
                                              projectcss.plasmic_default__inline,
                                              sty.link__vsZvw
                                            )}
                                            component={Link}
                                            href={
                                              "https://roamresearch.com/#/app/DiscourseGraphTemplate/page/ChgjmeLuR"
                                            }
                                            platform={"nextjs"}
                                          >
                                            {"Discourse Graph template"}
                                          </PlasmicLink__>
                                        }
                                        <React.Fragment>
                                          {
                                            " - get cracking building your graphs!"
                                          }
                                        </React.Fragment>
                                      </React.Fragment>
                                    </li>
                                  </ul>
                                }
                                <React.Fragment>{""}</React.Fragment>
                              </React.Fragment>
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </Stack__>
                </div>
              </Stack__>
              <VideoEmbed
                data-plasmic-name={"videoEmbed"}
                data-plasmic-override={overrides.videoEmbed}
                className={classNames("__wab_instance", sty.videoEmbed)}
              />
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__oxtSh)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__mJxw8)}
              id={"contact"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kj8Wn
                )}
              >
                {"Get involved: The Discourse Graph ecosystem"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__cdkvd)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uhbNo
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "Are you interested in generating grassroots knowledge with Discourse Graphs?  \n\nWe\u2019re building user-friendly discourse graph plugins in your favorite tool for thought! \n\n"
                      }
                    </React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__e5SF
                        )}
                        component={Link}
                        href={"mailto:discoursegraphs@protocol.ai"}
                        platform={"nextjs"}
                      >
                        {"Send us a line"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>
                      {" if you're interested in helping to "}
                    </React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__ze87U
                        )}
                        component={Link}
                        href={"https://github.com/DiscourseGraph"}
                        platform={"nextjs"}
                      >
                        {"develop"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{" or "}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__sph4O
                        )}
                        component={Link}
                        href={
                          "https://experiment.com/projects/sustainable-coordination-in-research-labs-via-graph-enabled-idea-boards/"
                        }
                        platform={"nextjs"}
                      >
                        {"beta-test"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>
                      {" these knowledge generation and synthesis tools. "}
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </Stack__>
            </Stack__>
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___26Yh)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__v0UQ)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1K2X8
                )}
              >
                {"\u00a9 Discourse Graphs 2024"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qoj9
                )}
              >
                {"Terms of Use | Privacy Policy"}
              </div>
            </Stack__>
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "videoEmbed"],
  videoEmbed: ["videoEmbed"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  videoEmbed: typeof VideoEmbed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDiscourseGraphsNew__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDiscourseGraphsNew__VariantsArgs;
    args?: PlasmicDiscourseGraphsNew__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDiscourseGraphsNew__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDiscourseGraphsNew__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDiscourseGraphsNew__ArgProps,
          internalVariantPropNames: PlasmicDiscourseGraphsNew__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDiscourseGraphsNew__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDiscourseGraphsNew";
  } else {
    func.displayName = `PlasmicDiscourseGraphsNew.${nodeName}`;
  }
  return func;
}

export const PlasmicDiscourseGraphsNew = Object.assign(
  // Top-level PlasmicDiscourseGraphsNew renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    videoEmbed: makeNodeComponent("videoEmbed"),

    // Metadata about props expected for PlasmicDiscourseGraphsNew
    internalVariantProps: PlasmicDiscourseGraphsNew__VariantProps,
    internalArgProps: PlasmicDiscourseGraphsNew__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "The Discourse Graphs Starter Pack",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDiscourseGraphsNew;
/* prettier-ignore-end */
